name: Generate Animation

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *" 
  
  # Allows manually running the job at any time
  workflow_dispatch:
  
  # Run on every push on the main branch
  push:
    branches:
      - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install canvas dependency
      - name: Install canvas dependency
        run: |
          npm install canvas

      # Generate the snake game SVG/GIF
      - name: Generate github-contribution-grid-snake.svg
        run: |
          npx -y @platane/snk@3.2.0 --user ${{ github.repository_owner }} --output dist/github-snake.svg
          npx -y @platane/snk@3.2.0 --user ${{ github.repository_owner }} --output dist/github-snake-dark.svg?palette=github-dark
          npx -y @platane/snk@3.2.0 --user ${{ github.repository_owner }} --output dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Push the generated SVG to the output branch
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
